blank_issues_enabled: true

contact_links:
  - name: 💬 Pomoc i dyskusja na Discordzie
    url: https://discord.gg/XjxpCuwvd
    about: Pytania dotyczące instalacji, konfiguracji, testów i działania Deye Energy Manager.
